"""Add created_by and deleted_at to Chat model

Revision ID: 2b94c2324484
Revises: create_chat_tables
Create Date: 2025-05-22 18:42:50.216950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2b94c2324484'
down_revision: Union[str, None] = 'create_chat_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_participants', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('chat_participants', 'updated_at')
    op.drop_column('chat_participants', 'id')
    op.add_column('chats', sa.Column('created_by', sa.UUID(), nullable=False))
    op.add_column('chats', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.alter_column('chats', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('chats', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('chats', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_foreign_key(None, 'chats', 'users', ['created_by'], ['id'])
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('messages', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint('messages_parent_message_id_fkey', 'messages', type_='foreignkey')
    op.drop_column('messages', 'message_type')
    op.drop_column('messages', 'role')
    op.drop_column('messages', 'parent_message_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('parent_message_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('messages', sa.Column('message_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.create_foreign_key('messages_parent_message_id_fkey', 'messages', 'messages', ['parent_message_id'], ['id'])
    op.alter_column('messages', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.alter_column('chats', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('chats', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('chats', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('chats', 'deleted_at')
    op.drop_column('chats', 'created_by')
    op.add_column('chat_participants', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('chat_participants', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.alter_column('chat_participants', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
