"""add chat type enum

Revision ID: 66718daa71bf
Revises: ac65067d815b
Create Date: 2025-05-23 16:31:50.082471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66718daa71bf'
down_revision: Union[str, None] = 'ac65067d815b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chats', 'type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('DIRECT', 'GROUP', name='chattype'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chats', 'type',
               existing_type=sa.Enum('DIRECT', 'GROUP', name='chattype'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
