"""add message_type and parent_message_id to messages

Revision ID: ac65067d815b
Revises: 2b94c2324484
Create Date: 2025-05-22 19:34:40.265900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac65067d815b'
down_revision: Union[str, None] = '2b94c2324484'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('message_type', sa.String(), nullable=False))
    op.add_column('messages', sa.Column('parent_message_id', sa.UUID(), nullable=True))
    op.add_column('messages', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'messages', 'messages', ['parent_message_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'deleted_at')
    op.drop_column('messages', 'parent_message_id')
    op.drop_column('messages', 'message_type')
    # ### end Alembic commands ###
